spring.application.name=Barbearia
spring.datasource.url=jdbc:postgresql://localhost:5432/barbearia
spring.datasource.username=postgres
spring.datasource.password=TROQUE_PELA_SENHA_REAL_DO_SEU_BANCO
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=TROQUE_POR_UMA_CHAVE_SECRETA_BEM_LONGA_SO_SUA_PELO_MENOS_32_CARACTERES
jwt.expiration=1296000000

server.tomcat.threads.max=10
server.tomcat.threads.min-spare=2
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2
